# Generated by Django 5.2.11 on 2026-02-25 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0002_alter_employee_employee_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255, unique=True)),
                ("device_name", models.CharField(max_length=255)),
                (
                    "device_brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "device_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("os_name", models.CharField(max_length=100)),
                ("os_version", models.CharField(max_length=100)),
                ("app_version", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
                "unique_together": {("employee", "device_id")},
            },
        ),
    ]
