# Generated by Django 5.2.11 on 2026-02-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
