# Generated by Django 5.2.11 on 2026-02-18 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0002_alter_employee_employee_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_start_time", models.TimeField(default="08:00:00")),
                ("work_end_time", models.TimeField(default="17:00:00")),
                ("late_tolerance_minutes", models.PositiveIntegerField(default=15)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attendance_settings",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "check_in_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "check_in_lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "check_in_location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "check_out_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "check_out_lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "check_out_location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "check_in_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="attendance/checkin/"
                    ),
                ),
                (
                    "check_out_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="attendance/checkout/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_time", "On Time"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                        ],
                        default="on_time",
                        max_length=20,
                    ),
                ),
                ("working_minutes", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "db_table": "attendances",
                "ordering": ["-date", "-check_in_time"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
