# Generated by Django 5.2.11 on 2026-02-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="working_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
