# Generated by Django 5.2.11 on 2026-02-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendance_working_hours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "ordering": ["-date"],
                "permissions": [("view_all", "Can view all attendance")],
            },
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_in_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_in_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_out_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_out_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("on_time", "On Time"), ("late", "Late"), ("alpha", "Alpha")],
                default="on_time",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="attendance",
            table=None,
        ),
    ]
